export interface contract {
    id: number,
    benA: String,
    benAQuocTich: String,
    benAChucVu: String,
    benADienThoai: String,
    benADaiDienCho: String,
    BenB: String,
    ngheNghiep: String,
    fkMaLoaiHD: String,
    hdTuNgay: Date,
    hdDenNgay: Date,
    hdFkMaBoMon: number,
    chucDanhChuyenMon: String,
    fkMaChucVu: String,
    cvPhaiLam: String,
    thoiGianLamViec: String,
    dCuLamViecCapPhat: String,
    phuongTienDiLai: String,
    fkIdNgach: String,
    fkIdBac: number,
    heSoLuong: number,
    hinhThucTraLuong: String,
    phuCapGom: String,
    thoiGianTraLuong: String,
    tienThuong: String,
    cheDoNangLuong: String,
    baoHoLDong: String,
    cheDoNghiNgoio: String,
    bhxhbhyt: String,
    cheDoDaoTao: String,
    quyenLoiDuocHuong: String,
    nhungThoaThuanKhac: String,
    boiThuong: String,
    hDLDLamTai: String,
    ghiChu: String,
    ngayKy: Date,
    thuViecTuNgay: Date,
    thuViecDenNgay: Date,
    c85PhanTram: number,
    soHopDong: String,
    noiDangKyBHYT: String,
    heSoLuongIn: String,
    canCu1: String,
    canCu2: String,
    huongKhoanThuong: String,
    bhytHDLV: String,
    donViLamViecIn: String,
    giaHan: number,
    fkMaCanBo: String,
    Loai_hop_dong?: {
        id: String,
        tenLoaiHopDong: String,
        kyTuVietTat: String,
        soThang: String
    },
    Ngach_cong_chuc?: {
        id: String,
        maSoNgach: String,
        nhom: String,
        tenNgach: String,
        soNamNangBac: number,
        tuVietTat: String,
        thuTuUuTien: number
    },
    Chuc_vu?: {
        id: String,
        ten_chuc_vu: String
    },
    Bo_mon?: {
        id: Number,
        bomonId: String,
        ten_bo_mon: String,
        ma_khoa: String,
        ma_bo_mon_truong: String,
        xoa: number,
        cap_khoa: String
    },
    Bac_luong?: {
        id: number,
        heSoLuong: number,
        ngayBatDauHieuLuc: Date,
        ngayHetHieuLuc: Date,
        fkIdNgach: String,
        fkIdNhom: String
    },
    Can_bo_giang_day?: {
        id: String,
        ho: String,
        ten: String,

    }
}