import { BreadcrumbsRoute } from "use-react-router-breadcrumbs";

export const routesAdmin: BreadcrumbsRoute[] = [
    {
        path: "/admin/personalmanagement",
        breadcrumb: "Danh sách nhân sự",
        props: { root: true },
    },
    { path: "/admin/personalmanagement/add", breadcrumb: "Thêm nhân sự" },
    { path: "/admin/personalmanagement/:id", breadcrumb: "Chi tiết nhân sự" },
    { path: "/admin/personalmanagement/update/:id", breadcrumb: "Cập nhật nhân sự" },
    {
        path: "/admin/businessmanagement/domestic",
        breadcrumb: "Danh sách công tác trong nước",
        props: { root: true },
    },
    { path: "/admin/businessmanagement/domestic/add", breadcrumb: "Thêm công tác trong nước" },
    { path: "/admin/businessmanagement/domestic/:id", breadcrumb: "Chi tiết công tác trong nước" },
    { path: "/admin/businessmanagement/domestic/update/:id", breadcrumb: "Cập nhật công tác trong nước" },
    {
        path: "/admin/businessmanagement/foreign",
        breadcrumb: "Danh sách công tác ngoài nước",
        props: { root: true },
    },
    { path: "/admin/businessmanagement/foreign/add", breadcrumb: "Thêm công tác ngoài nước" },
    { path: "/admin/businessmanagement/foreign/:id", breadcrumb: "Chi tiết công tác ngoài nước" },
    { path: "/admin/businessmanagement/foreign/update/:id", breadcrumb: "Cập nhật công tác ngoài nước" },
    {
        path: "/admin/trainingmanagement",
        breadcrumb: "Danh sách bồi dưỡng",
        props: { root: true },
    },
    { path: "/admin/trainingmanagement/add", breadcrumb: "Thêm bồi dưỡng" },
    { path: "/admin/trainingmanagement/:id", breadcrumb: "Chi tiết bồi dưỡng" },
    { path: "/admin/trainingmanagement/update/:id", breadcrumb: "Cập nhật bồi dưỡng" },
    {
        path: "/admin/rewardmanagement",
        breadcrumb: "Danh sách khen thưởng",
        props: { root: true },
    },
    { path: "/admin/rewardmanagement/add", breadcrumb: "Thêm khen thưởng" },
    { path: "/admin/rewardmanagement/:id", breadcrumb: "Chi tiết khen thưởng" },
    { path: "/admin/rewardmanagement/update/:id", breadcrumb: "Cập nhật khen thưởng" },
    {
        path: "/admin/disciplinemanagement",
        breadcrumb: "Danh sách kỹ luật",
        props: { root: true },
    },
    { path: "/admin/disciplinemanagement/add", breadcrumb: "Thêm kỹ luật" },
    { path: "/admin/disciplinemanagement/:id", breadcrumb: "Chi tiết kỹ luật" },
    { path: "/admin/disciplinemanagement/update/:id", breadcrumb: "Cập nhật kỹ luật" },
    {
        path: "/admin/cultivatemanagement",
        breadcrumb: "Danh sách kỹ đào tạo",
        props: { root: true },
    },
    { path: "/admin/cultivatemanagement/add", breadcrumb: "Thêm kỹ luật" },
    { path: "/admin/cultivatemanagement/:id", breadcrumb: "Chi tiết kỹ đào tạo" },
    { path: "/admin/cultivatemanagement/update/:id", breadcrumb: "Cập nhật kỹ đào tạo" },
]
export const routesUser: BreadcrumbsRoute[] = [
    {
        path: "/user/detail",
        breadcrumb: "Thông tin cá nhân",
        props: { root: true },
    },
    {
        path: "/user/businessmanagement/domestic",
        breadcrumb: "Danh sách công tác trong nước",
        props: { root: true },
    },
    { path: "/user/businessuser/domestic/add", breadcrumb: "Thêm công tác trong nước" },
    { path: "/user/businessuser/domestic/:id", breadcrumb: "Chi tiết công tác trong nước" },
    { path: "/user/businessuser/domestic/update/:id", breadcrumb: "Cập nhật công tác trong nước" },
    {
        path: "/user/businessuser/foreign",
        breadcrumb: "Danh sách công tác ngoài nước",
        props: { root: true },
    },
    { path: "/user/businessuser/foreign/add", breadcrumb: "Thêm công tác ngoài nước" },
    { path: "/user/businessuser/foreign/:id", breadcrumb: "Chi tiết công tác ngoài nước" },
    { path: "/user/businessuser/foreign/update/:id", breadcrumb: "Cập nhật công tác ngoài nước" },
    {
        path: "/user/traininguser",
        breadcrumb: "Danh sách bồi dưỡng",
        props: { root: true },
    },
    { path: "/user/traininguser/add", breadcrumb: "Thêm bồi dưỡng" },
    { path: "/user/traininguser/:id", breadcrumb: "Chi tiết bồi dưỡng" },
    { path: "/user/traininguser/update/:id", breadcrumb: "Cập nhật bồi dưỡng" },
    {
        path: "/user/rewarduser",
        breadcrumb: "Danh sách khen thưởng",
        props: { root: true },
    },
    { path: "/user/rewarduser/add", breadcrumb: "Thêm khen thưởng" },
    { path: "/user/rewarduser/:id", breadcrumb: "Chi tiết khen thưởng" },
    { path: "/user/rewarduser/update/:id", breadcrumb: "Cập nhật khen thưởng" },
    {
        path: "/user/disciplineuser",
        breadcrumb: "Danh sách kỹ luật",
        props: { root: true },
    },
    { path: "/user/disciplineuser/add", breadcrumb: "Thêm kỹ luật" },
    { path: "/user/disciplineuser/:id", breadcrumb: "Chi tiết kỹ luật" },
    { path: "/user/disciplineuser/update/:id", breadcrumb: "Cập nhật kỹ luật" },
    {
        path: "/user/cultivateuser",
        breadcrumb: "Danh sách kỹ đào tạo",
        props: { root: true },
    },
    { path: "/user/cultivateuser/add", breadcrumb: "Thêm kỹ luật" },
    { path: "/user/cultivateuser/:id", breadcrumb: "Chi tiết kỹ đào tạo" },
    { path: "/user/cultivateuser/update/:id", breadcrumb: "Cập nhật kỹ đào tạo" },
]